// GENERATED by scripts/sync-core.mjs from packages/orchestrator/src/proposal.ts — do not edit here.
/**
 * What can honestly be proposed for a finding before anything is run.
 *
 * When the app is going to carry the fix out for real (a branch, an edit, the
 * project's tests, a re-check, a commit), the assessment must not pre-fill those
 * results. This builds the finding's remediation slot with only what is already
 * true: the branch the fix would go on, the root cause, and — when the rule has a
 * genuine rewrite — the exact diff of that rewrite against the real file. A rule
 * that can only offer a FIXME scaffold proposes no diff at all; that fix has to be
 * written by an agent or a person.
 */
import type { Finding } from "../core/types";
import { applyEdit, diffTexts, isConcrete, ruleEdit, ruleOf } from "../core/fixes";

export const fixBranch = (finding: Finding) => `arcade/fix-${finding.id.toLowerCase()}-${ruleOf(finding)?.id ?? "finding"}`;

export function proposeFix(finding: Finding, source: string | undefined): Finding {
  const edit = ruleEdit(finding);
  const concrete = !!edit && isConcrete(edit.edit) && source != null;
  let files: Finding["remediation"]["files"] = [];
  if (concrete) {
    try {
      files = [diffTexts(finding.vulnerableCode.path, source, applyEdit(source, edit.line, edit.edit))];
    } catch {
      files = []; // the file changed since the scan; the real run re-reads it
    }
  }
  return {
    ...finding,
    remediation: {
      branch: fixBranch(finding),
      commit: "",
      summary: `fix(${finding.id.toLowerCase()}): ${concrete ? edit.edit.note : (finding.mitigations[0]?.title ?? `close ${finding.title.toLowerCase()}`)}`,
      rootCause: finding.remediation.rootCause,
      files,
      tests: [],
      commands: [],
    },
    verification: { ...finding.verification, outcome: "pending", independent: true, replaySummary: "", statusBefore: "present", statusAfter: "—", mutatedPayloads: 0, mutatedSucceeded: 0, regressionPassed: 0, regressionTotal: 0 },
  };
}
