/**
 * Source tree for the bundled sample project (acme-commerce), so the explorer
 * and editor have something real to show in a dry run.
 *
 * The files ARC-001 touches are assembled from the same demo data the run
 * uses (FLAGSHIP.vulnerableCode / remediation diffs), so the flagged line
 * numbers and the proposed diff always line up with what the editor shows.
 */
import { FLAGSHIP } from "./demo";
import { memoryFs, type WorkspaceFs } from "./fs";
import type { RemediationFile } from "./types";

/** Places `body` so its first line is `startLine`, whatever the header's length. */
function at(startLine: number, head: string[], body: string[]): string {
  const lead = head.slice(0, startLine - 1);
  while (lead.length < startLine - 1) lead.push("");
  return [...lead, ...body, ""].join("\n");
}

const side = (f: RemediationFile, keep: "del" | "add") => f.diff.filter((l) => l.kind === "context" || l.kind === keep).map((l) => l.text);
const firstLine = (f: RemediationFile) => f.diff.find((l) => l.oldNo != null)?.oldNo ?? 1;
const remediated = (path: string) => FLAGSHIP.remediation.files.find((f) => f.path === path)!;

const EXPORT_HEAD = [
  "import { json } from '../../lib/http'",
  "import { db } from '../../lib/db'",
  "import { validateSession } from '../../auth/session'",
  "",
  "/**",
  " * Admin export — streams order records as JSON.",
  " *",
  " * Used by the back-office dashboard to pull a full data dump.",
  " * Scaffolded by the coding agent; not reviewed.",
  " */",
  "",
];

const SESSION_HEAD = [
  "import { verify } from 'jsonwebtoken'",
  "import { env } from '../lib/env'",
  "",
  "export interface Session {",
  "  userId: string",
  "  role?: 'admin' | 'standard'",
  "  tenantId?: string",
  "}",
  "",
  "const COOKIE = 'session'",
  "",
  "/** Pulls the raw JWT out of the Cookie header. */",
  "function readToken(req: Request): string | null {",
  "  const cookies = req.headers.get('cookie') ?? ''",
  "  for (const part of cookies.split(';')) {",
  "    const [name, ...rest] = part.trim().split('=')",
  "    if (name === COOKIE) return rest.join('=')",
  "  }",
  "  return null",
  "}",
  "",
  "function signingKey(): string {",
  "  if (!env.JWT_SECRET) throw new Error('JWT_SECRET is not set')",
  "  return env.JWT_SECRET",
  "}",
  "",
  "/**",
  " * Confirms the request carries a valid session token.",
  " *",
  " * Returns null for a missing or invalid token. Callers treat any",
  " * non-null result as \"signed in\".",
  " */",
  "export async function validateSession(req: Request) {",
  "  const token = readToken(req)",
  "  if (!token) return null",
  "  const key = signingKey()",
  "",
  "  // verify() throws on a bad signature or an expired token;",
  "  // the gateway turns that into a 401.",
];

const STATIC_FILES: Record<string, string> = {
  "package.json": `{
  "name": "acme-commerce",
  "version": "0.4.1",
  "private": true,
  "scripts": {
    "dev": "next dev",
    "build": "next build",
    "test": "vitest run",
    "db:migrate": "prisma migrate deploy"
  },
  "dependencies": {
    "@prisma/client": "^6.2.0",
    "jsonwebtoken": "^9.0.2",
    "next": "15.1.0",
    "pg": "^8.13.1",
    "stripe": "^17.5.0"
  },
  "devDependencies": {
    "prisma": "^6.2.0",
    "typescript": "^5.7.2",
    "vitest": "^2.1.8"
  }
}
`,
  "README.md": `# acme-commerce

Commerce backend for the Acme storefront. Next.js route handlers in front of
PostgreSQL, with Stripe for payments.

## Services

- \`web\` — storefront and account pages
- \`api-gateway\` — everything under \`src/api\`
- \`orders-service\` — order reads and writes
- \`admin-service\` — back-office exports

## Running locally

\`\`\`sh
cp .env.example .env
npm install
npm run db:migrate
npm run dev
\`\`\`

> Most of this codebase was generated by a coding agent and has not had a
> security review.
`,
  ".env.example": `DATABASE_URL=postgres://acme:acme@localhost:5432/acme
JWT_SECRET=change-me
# Test key — rotate before launch
STRIPE_SECRET_KEY=sk_test_51Nf2aKExampleOnlyNotARealKey00
`,
  "prisma/schema.prisma": `datasource db {
  provider = "postgresql"
  url      = env("DATABASE_URL")
}

model User {
  id       String  @id @default(cuid())
  email    String  @unique
  role     String  @default("standard")
  tenantId String
  orders   Order[]
}

model Order {
  id       Int     @id @default(autoincrement())
  userId   String
  tenantId String
  total    Decimal
  user     User    @relation(fields: [userId], references: [id])
}
`,
  "src/lib/http.ts": `export function json(body: unknown, status = 200): Response {
  return new Response(JSON.stringify(body), {
    status,
    headers: { 'content-type': 'application/json' },
  })
}
`,
  "src/lib/db.ts": `import { Pool } from 'pg'
import { env } from './env'

const pool = new Pool({ connectionString: env.DATABASE_URL })

export const db = {
  async query<T = unknown>(sql: string, params: unknown[] = []): Promise<T[]> {
    const res = await pool.query(sql, params)
    return res.rows as T[]
  },
}
`,
  "src/lib/env.ts": `export const env = {
  DATABASE_URL: process.env.DATABASE_URL ?? '',
  JWT_SECRET: process.env.JWT_SECRET ?? '',
  STRIPE_SECRET_KEY: process.env.STRIPE_SECRET_KEY ?? '',
}
`,
  "src/api/orders.ts": `import { json } from '../lib/http'
import { db } from '../lib/db'
import { validateSession } from '../auth/session'

export async function GET(req: Request) {
  const session = await validateSession(req)
  if (!session) return json({ error: 'unauthenticated' }, 401)

  const id = new URL(req.url).searchParams.get('id')
  if (id) {
    // ARC-002: the id is concatenated straight into the statement
    const rows = await db.query('SELECT * FROM orders WHERE id = ' + id)
    return json({ order: rows[0] ?? null })
  }

  const rows = await db.query('SELECT * FROM orders WHERE user_id = $1', [session.userId])
  return json({ orders: rows })
}
`,
  "src/api/auth/verify.ts": `import { decode, verify } from 'jsonwebtoken'
import { json } from '../../lib/http'
import { env } from '../../lib/env'

export async function POST(req: Request) {
  const { token } = await req.json()
  const header = decode(token, { complete: true })?.header

  // ARC-003: an unsigned token skips verification entirely
  if (header?.alg === 'none') return json({ valid: true, claims: decode(token) })

  try {
    return json({ valid: true, claims: verify(token, env.JWT_SECRET) })
  } catch {
    return json({ valid: false }, 401)
  }
}
`,
  "tests/orders.test.ts": `import { expect, test } from 'vitest'
import { get, loginAs } from './helpers'

test('a user only sees their own orders', async () => {
  const cookie = await loginAs('standard')
  const res = await get('/api/orders', { cookie })
  expect(res.status).toBe(200)
  expect(res.body.orders.every((o: { userId: string }) => o.userId === 'u_standard')).toBe(true)
})
`,
};

const EXPORT = remediated("src/api/admin/export.ts");
const SESSION = remediated("src/auth/session.ts");

/** The sample tree before or after the remediator's fix for ARC-001 lands. */
export function sampleFs(fixed: boolean): WorkspaceFs {
  const keep = fixed ? "add" : "del";
  const files: Record<string, string> = {
    ...STATIC_FILES,
    [EXPORT.path]: at(firstLine(EXPORT), EXPORT_HEAD, side(EXPORT, keep)),
    [SESSION.path]: at(firstLine(SESSION), SESSION_HEAD, side(SESSION, keep)),
  };
  if (fixed) {
    for (const f of FLAGSHIP.remediation.files) if (f.status === "A") files[f.path] = [...side(f, "add"), ""].join("\n");
  }
  return memoryFs(files);
}
