// GENERATED by scripts/sync-core.mjs from packages/agents/src/attacker.ts — do not edit here.
/**
 * Attacker — reproduces each weakness against the imported code, in the sandbox.
 *
 * "Reproduce" here is static and safe: the attacker confirms the vulnerable
 * pattern is present and reachable, pins it to exact lines, and records evidence
 * describing *why* it is reachable — the code path, not a runnable exploit. It
 * produces no weaponized payloads and touches no live system; the target is the
 * user's own source, read in an isolated process.
 *
 * Output is the `Finding` shape the whole app already renders.
 */
import type { Evidence, Finding } from "../core/types";
import type { Hit, Scan } from "../core/scanner";

const stamp = () => {
  const d = new Date();
  const p = (n: number) => String(n).padStart(2, "0");
  return `${p(d.getHours())}:${p(d.getMinutes())}:${p(d.getSeconds())}`;
};

/** Try to read a route path out of a file location, else fall back to the file. */
function targetOf(hit: Hit): string {
  const p = hit.path.replace(/\\/g, "/");
  const api = p.search(/\/api\//);
  if (api >= 0) {
    return p.slice(api).replace(/\/route\.(t|j)sx?$/, "").replace(/\.(t|j)sx?$/, "") || p;
  }
  return `${hit.path}:${hit.match.line}`;
}

/** A window of source around the match, with the offending line flagged. */
function codeWindow(source: string | undefined, line: number) {
  if (!source) return { lines: [] as { no: number; text: string; flagged?: boolean }[] };
  const all = source.split("\n");
  const from = Math.max(0, line - 4);
  const to = Math.min(all.length, line + 2);
  const lines = [];
  // A CRLF file split on "\n" leaves "\r" on every line; nothing downstream wants it.
  for (let i = from; i < to; i++) lines.push({ no: i + 1, text: all[i].replace(/\r$/, ""), flagged: i + 1 === line });
  return { lines };
}

/**
 * What a static match actually establishes, and nothing more: which rule fired, where, and on
 * what text. No request was sent and nothing ran, so there is no response and no reproduction
 * to claim. `method: "STATIC"` is what tells a view to present it that way.
 */
function evidenceFor(hit: Hit): Evidence {
  const loc = `${hit.path}:${hit.match.line}`;
  return {
    method: "STATIC",
    target: loc,
    requestHeaders: [`rule: ${hit.rule.id}`, "analysis: static · source only · nothing executed"],
    requestBody: hit.match.captured ? `matched: ${hit.match.captured.slice(0, 120)}` : undefined,
    statusBefore: "pattern present",
    responseBody: hit.match.excerpt,
    steps: [
      `The ${hit.rule.id} rule (${hit.rule.cwe.split("·")[0].trim()}) matched at ${loc}.`,
      hit.rule.attackNarrative,
      "This is a static match: no request was sent and no code ran, so whether the line is reachable at runtime has not been confirmed. Read the code around it before acting.",
    ],
    artifact: "exported on demand",
    capturedAt: stamp(),
  };
}

/** Build one finding from one hit. `index` produces the ARC-xxx id. */
export function toFinding(hit: Hit, index: number, scan: Scan): Finding {
  const id = `ARC-${String(index + 1).padStart(3, "0")}`;
  const source = scan.sources[hit.path];
  const at = `${hit.path}:${hit.match.line}`;
  return {
    id,
    title: hit.rule.title,
    severity: hit.rule.severity,
    status: "reproduced",
    target: targetOf(hit),
    ruleId: hit.rule.id,
    cwe: hit.rule.cwe,
    summary: hit.rule.summary,
    description: `${hit.rule.description} Found at ${at}.`,
    attackNarrative: hit.rule.attackNarrative,
    vulnerableCode: { path: hit.path, ...codeWindow(source, hit.match.line) },
    evidence: evidenceFor(hit),
    mitigations: hit.rule.mitigations,
    // Filled by the remediator; empty until then.
    remediation: { branch: "", commit: "", summary: "", rootCause: "", files: [], tests: [], commands: [] },
    verification: {
      outcome: "pending",
      independent: true,
      replaySummary: "",
      statusBefore: "reachable",
      statusAfter: "—",
      mutatedPayloads: 0,
      mutatedSucceeded: 0,
      regressionPassed: 0,
      regressionTotal: 0,
    },
    timeline: [],
    agent: "Attacker",
    createdAt: stamp(),
  };
}

/** Deterministic sandbox id from the set of files touched. */
export function sandboxId(scan: Scan): string {
  let h = 0;
  for (const p of scan.paths.slice(0, 200)) for (let i = 0; i < p.length; i++) h = (h * 31 + p.charCodeAt(i)) | 0;
  return `sandbox-${(h >>> 0).toString(16).slice(0, 4)}`;
}

/** Turn every hit into a finding, strongest first (hits are already sorted). */
export function reproduce(scan: Scan): Finding[] {
  return scan.hits.map((hit, i) => toFinding(hit, i, scan));
}
