// GENERATED by scripts/sync-core.mjs from packages/agents/src/defender.ts — do not edit here.
/**
 * Defender — traces root cause and ranks the fixes.
 *
 * The rules already carry ranked mitigations; the defender's job is to turn a
 * reproduced finding into an explained one: a plain-language root cause and the
 * ordered choices, recommended first. With a model provider it deepens the root
 * cause from the surrounding source; locally it derives it from the rule and the
 * finding's location.
 */
import type { Finding, Mitigation } from "../core/types";
import type { AssessmentProvider } from "./provider";

function localRootCause(finding: Finding): string {
  const where = finding.vulnerableCode.path;
  const cwe = finding.cwe.split("·")[0].trim();
  return `${cwe}: the weakness in ${where} comes from ${firstClause(finding.description)}. ${finding.mitigations[0]?.detail ?? ""}`.trim();
}

const firstClause = (s: string) => {
  const m = s.match(/^[^.]+\./);
  return (m ? m[0] : s).replace(/\.$/, "").toLowerCase();
};

/** Order mitigations recommended-first, then by ascending effort. */
function rank(mitigations: Mitigation[]): Mitigation[] {
  const effort = { low: 0, medium: 1, high: 2 };
  return [...mitigations].sort((a, b) => Number(b.recommended) - Number(a.recommended) || effort[a.effort] - effort[b.effort]);
}

export async function defend(finding: Finding, source: string, provider: AssessmentProvider): Promise<Finding> {
  let patch: Partial<Finding> | null = null;
  if (provider.explain) {
    try {
      patch = await provider.explain(finding, source);
    } catch {
      patch = null;
    }
  }
  const mitigations = rank(patch?.mitigations ?? finding.mitigations);
  return {
    ...finding,
    ...patch,
    mitigations,
    status: "analyzing",
    remediation: {
      ...finding.remediation,
      rootCause: patch?.remediation?.rootCause || localRootCause(finding),
    },
  };
}
