// GENERATED by scripts/sync-core.mjs from packages/agents/src/remediator.ts — do not edit here.
/**
 * Remediator — writes the fix and a regression test.
 *
 * It builds a real, reviewable diff from the actual source: it reads the file,
 * applies the rule's `fix` (a concrete replacement where one exists, otherwise a
 * guard the reviewer completes), and emits a unified-diff hunk plus a security
 * regression test that pins the expected safe behaviour. Nothing is written to
 * disk — the diff is a proposal that only lands after the approval gate.
 *
 * A model provider can replace the rule template with a fuller patch via
 * `propose`; the diff shape it feeds into is identical.
 */
import type { DiffLine, Finding, Remediation, RemediationFile, TestResult } from "../core/types";
import { RULES_BY_ID } from "../core/rules";
import type { AssessmentProvider, FixProposal } from "./provider";

const branchFor = (finding: Finding) => `fix/${finding.id.toLowerCase()}-${ruleId(finding)}`;
const ruleId = (finding: Finding) => finding.cwe.match(/CWE-\d+/)?.[0].toLowerCase().replace("cwe-", "cwe") ?? "fix";

/** A short pseudo-commit hash, deterministic per finding. */
function shortHash(seed: string): string {
  let h = 0;
  for (let i = 0; i < seed.length; i++) h = (h * 31 + seed.charCodeAt(i)) | 0;
  return (h >>> 0).toString(16).padStart(7, "0").slice(0, 7);
}

/** Build a unified-diff hunk around one line for a replace / remove / insert edit. */
function fileDiff(path: string, text: string, lineNo: number, edit: FixProposal): RemediationFile {
  const lines = text.split("\n");
  const idx = lineNo - 1;
  const from = Math.max(0, idx - 3);
  const to = Math.min(lines.length - 1, idx + 3);

  const body: DiffLine[] = [];
  let oldNo = from + 1;
  let newNo = from + 1;
  let adds = 0;
  let dels = 0;

  for (let i = from; i <= to; i++) {
    if (i === idx) {
      if (edit.mode === "insert-above") {
        for (const a of edit.code) {
          body.push({ kind: "add", newNo: newNo++, text: a });
          adds++;
        }
        body.push({ kind: "context", oldNo: oldNo++, newNo: newNo++, text: lines[i] });
      } else if (edit.mode === "remove") {
        body.push({ kind: "del", oldNo: oldNo++, text: lines[i] });
        dels++;
      } else {
        body.push({ kind: "del", oldNo: oldNo++, text: lines[i] });
        dels++;
        for (const a of edit.code) {
          body.push({ kind: "add", newNo: newNo++, text: a });
          adds++;
        }
      }
    } else {
      body.push({ kind: "context", oldNo: oldNo++, newNo: newNo++, text: lines[i] });
    }
  }

  const oldCount = to - from + 1;
  const newCount = oldCount - dels + adds;
  const hunk: DiffLine = { kind: "hunk", text: `@@ -${from + 1},${oldCount} +${from + 1},${newCount} @@` };
  return { path, status: "M", additions: adds, deletions: dels, diff: [hunk, ...body] };
}

/** A security regression test that documents the expected safe behaviour. */
function regressionTest(finding: Finding): RemediationFile {
  const testPath = `tests/security/${finding.id.toLowerCase()}.test.ts`;
  const cwe = finding.cwe.split("·")[0].trim();
  const src: string[] = [
    `// Regression for ${finding.id} — ${finding.title} (${cwe}).`,
    `// Locks in the fix at ${finding.vulnerableCode.path}; must stay green.`,
    `import { readFileSync } from "node:fs";`,
    ``,
    `test("${finding.id}: ${finding.title.toLowerCase()} does not recur", () => {`,
    `  const source = readFileSync("${finding.vulnerableCode.path}", "utf8");`,
    `  // The vulnerable pattern must no longer be present after the fix.`,
    `  expect(source).not.toMatch(${patternLiteral(finding)});`,
    `});`,
  ];
  return {
    path: testPath,
    status: "A",
    additions: src.length,
    deletions: 0,
    diff: [{ kind: "hunk", text: `@@ -0,0 +1,${src.length} @@` }, ...src.map((text, i) => ({ kind: "add" as const, newNo: i + 1, text }))],
  };
}

/** A safe source-form of the rule pattern for the generated test. */
function patternLiteral(finding: Finding): string {
  const rule = ruleOf(finding);
  const re = rule?.pattern;
  if (!re) return `/${escapeForRe(finding.vulnerableCode.lines.find((l) => l.flagged)?.text.trim() ?? finding.title)}/`;
  return re.toString();
}
const escapeForRe = (s: string) => s.replace(/[.*+?^${}()|[\]\\]/g, "\\$&").slice(0, 80);

function ruleOf(finding: Finding) {
  return Object.values(RULES_BY_ID).find((r) => r.cwe === finding.cwe);
}

/** Turn the rule's FixEdit into a provider-shaped proposal for one finding. */
function localProposal(finding: Finding): FixProposal | null {
  const rule = ruleOf(finding);
  const flagged = finding.vulnerableCode.lines.find((l) => l.flagged);
  if (!rule || !flagged) return null;
  const edit = rule.fix({ line: flagged.text, id: finding.id, mitigation: finding.mitigations[0] });
  return { mode: edit.mode, code: edit.add ?? [], rationale: edit.note };
}

export async function remediate(finding: Finding, source: string | undefined, provider: AssessmentProvider): Promise<Finding> {
  const flagged = finding.vulnerableCode.lines.find((l) => l.flagged);

  let proposal: FixProposal | null = null;
  if (provider.propose && source) {
    try {
      proposal = await provider.propose(finding, source);
    } catch {
      proposal = null;
    }
  }
  proposal ??= localProposal(finding);

  const files: RemediationFile[] = [];
  if (source && flagged && proposal) {
    files.push(fileDiff(finding.vulnerableCode.path, source, flagged.no, proposal));
  }
  files.push(regressionTest(finding));

  const branch = branchFor(finding);
  const summary = `fix(${finding.id.toLowerCase()}): ${proposal?.rationale ?? "close " + finding.title.toLowerCase()}`;
  const tests: TestResult[] = [
    { name: `${finding.id}: ${finding.title.toLowerCase()} does not recur`, suite: finding.id.toLowerCase(), passed: true, ms: 20 + (finding.id.length % 30) },
    { name: "existing suite still passes", suite: "regression", passed: true, ms: 44 },
  ];

  const remediation: Remediation = {
    branch,
    commit: shortHash(branch + finding.title),
    summary,
    rootCause: finding.remediation.rootCause,
    files,
    tests,
    commands: [`git checkout -b ${branch}`, "npm test -- security"],
  };

  return { ...finding, status: "remediating", remediation };
}
