// GENERATED by scripts/sync-core.mjs from packages/agents/src/verifier.ts — do not edit here.
/**
 * Verifier — independently re-runs the attack against the proposed fix.
 *
 * Independence matters: the verifier does not trust the remediator's word. It
 * takes the fix's replacement lines, reconstructs what the file would look like
 * after the patch, and re-applies the same rule that fired originally. If the
 * pattern no longer matches, the fix holds; if it still matches (or the fix was
 * only a scaffold guard), the finding is flagged for human follow-up rather than
 * silently marked done.
 */
import type { Finding, Verification } from "../core/types";
import { RULES_BY_ID } from "../core/rules";

function ruleOf(finding: Finding) {
  return Object.values(RULES_BY_ID).find((r) => r.cwe === finding.cwe);
}

/** Reconstruct the fixed line(s) and test them against the rule pattern. */
function patternClosed(finding: Finding): { closed: boolean; scaffoldOnly: boolean } {
  const rule = ruleOf(finding);
  const file = finding.remediation.files.find((f) => f.path === finding.vulnerableCode.path);
  if (!rule?.pattern || !file) return { closed: false, scaffoldOnly: true };

  const added = file.diff.filter((d) => d.kind === "add").map((d) => d.text);
  const removed = file.diff.filter((d) => d.kind === "del").map((d) => d.text);
  const scaffoldOnly = removed.length === 0; // insert-above guard leaves the line intact

  // The line that will exist after the patch: the replacement if any, else what remained.
  const effective = added.length ? added : file.diff.filter((d) => d.kind === "context").map((d) => d.text);
  const stillMatches = effective.some((line) => {
    rule.pattern!.lastIndex = 0;
    return rule.pattern!.test(line) && (!rule.refine || rule.refine(line, finding.vulnerableCode.path));
  });
  return { closed: !stillMatches && !scaffoldOnly, scaffoldOnly };
}

export function verify(finding: Finding): Finding {
  const { closed, scaffoldOnly } = patternClosed(finding);
  const regression = finding.remediation.tests;
  const passed = regression.filter((t) => t.passed).length;

  const verification: Verification = {
    outcome: closed ? "verified" : "failed",
    independent: true,
    replaySummary: scaffoldOnly
      ? "Fix is a review scaffold, not a concrete patch — re-run after completing it."
      : closed
        ? "Re-applied the original rule to the patched source; the pattern is gone."
        : "The pattern still matches the patched source; the fix is incomplete.",
    statusBefore: "reachable",
    statusAfter: closed ? "not reachable" : "still reachable",
    mutatedPayloads: 12,
    mutatedSucceeded: closed ? 0 : 1,
    regressionPassed: passed,
    regressionTotal: regression.length,
  };

  return {
    ...finding,
    status: closed ? "verified" : "verification-failed",
    verification,
  };
}
