// GENERATED by scripts/sync-core.mjs from packages/core/src/engine.ts — do not edit here.
/**
 * Pure run engine for the Arcade demo — no React.
 *
 * A run is an ordered list of "beats" (state transforms). The store (store.ts)
 * plays them on a timer and pauses at approval gates; this module holds the
 * beat construction and the pure `applyBeat` reducer so they can be unit-tested
 * independently of React.
 */
import type { Agent, AgentKind, ApprovalKind, ArcadeState, Finding, RunPhase, TerminalLine, TimelineEvent, Verification } from "./types";
import {
  ENVIRONMENT,
  FLAGSHIP,
  initialAgents,
  initialSurface,
  PROJECT,
  PROVIDERS,
  SCRIPTS,
  SECONDARY_FINDINGS,
  WORKSPACES,
} from "./demo";

export type Beat =
  | { delay: number; t: "phase"; phase: RunPhase }
  | { delay: number; t: "term"; line: TerminalLine }
  | { delay: number; t: "timeline"; ev: TimelineEvent }
  | { delay: number; t: "agent"; kind: AgentKind; patch: Partial<Agent> }
  | { delay: number; t: "reveal"; n: number }
  | { delay: number; t: "finding"; patch: Partial<Finding> }
  | { delay: number; t: "verify"; patch: Partial<Verification> }
  | { delay: number; t: "gate"; approvalId: string; def?: GateDef };

/** Inline approval definition carried by a live run's gate beat. */
export interface GateDef {
  kind: ApprovalKind;
  title: string;
  reason: string;
  target: string;
  evidence?: string;
  approveLabel?: string;
}

/** A ready-to-play run: the ordered beats and the state they start from. */
export interface RunPlan {
  beats: Beat[];
  initial: ArcadeState;
}

export const TERM = 340; // ms between streamed terminal lines
export const STEP = 160; // ms for small state updates

export function freshState(): ArcadeState {
  return {
    project: PROJECT,
    environment: ENVIRONMENT,
    workspaces: WORKSPACES,
    providers: PROVIDERS,
    agents: initialAgents(),
    surface: initialSurface(),
    finding: { ...FLAGSHIP, timeline: [] },
    secondaryFindings: SECONDARY_FINDINGS,
    approvals: [],
    timeline: [],
    terminal: [
      { agent: "system", kind: "plain", text: "arcade v0.1.0 · target sandbox-7f2c (isolated, disposable)" },
      { agent: "system", kind: "plain", text: 'Run the security loop with the "Run demo" control, or `arcade scan .`' },
    ],
    phase: "idle",
    revealedNodes: 0,
  };
}

export const APPROVAL_DEFS: Record<string, GateDef> = {
  "approve-fix": {
    kind: "code",
    title: "Apply the proposed fix",
    reason: "The remediation agent wants to modify authorization logic to close ARC-001.",
    target: "src/api/admin/export.ts · src/auth/session.ts",
  },
  "approve-merge": {
    kind: "ship",
    title: "Merge the verified fix to main",
    reason: "ARC-001 is verified fixed (200 OK → 403 Forbidden). Merging closes the finding.",
    target: "fix/admin-export-authz → main",
    evidence: "ARC-001 verified fixed · original exploit returns 403 · 156/156 tests pass",
    approveLabel: "Approve & merge",
  },
};

/** Build the full beat sequence for one loop over the flagship finding. */
export function buildBeats(): Beat[] {
  const beats: Beat[] = [];
  const term = (line: TerminalLine, delay = TERM) => beats.push({ t: "term", line, delay });
  const time = (ev: TimelineEvent) => beats.push({ t: "timeline", ev, delay: STEP });
  const agent = (kind: AgentKind, patch: Partial<Agent>, delay = STEP) => beats.push({ t: "agent", kind, patch, delay });
  const phase = (p: RunPhase) => beats.push({ t: "phase", phase: p, delay: STEP });
  const reveal = (n: number) => beats.push({ t: "reveal", n, delay: 220 });
  const finding = (patch: Partial<Finding>) => beats.push({ t: "finding", patch, delay: STEP });

  // ---- Map -----------------------------------------------------------------
  phase("mapping");
  agent("mapper", { status: "running", task: "Reading the project", progress: 0.1 }, 120);
  SCRIPTS.mapping.terminal.forEach((l, i) => {
    term(l);
    if (i === 1) reveal(3);
    if (i === 3) reveal(6);
    if (i === 5) reveal(9);
    agent("mapper", { progress: (i + 1) / SCRIPTS.mapping.terminal.length });
  });
  SCRIPTS.mapping.timeline.forEach(time);
  agent("mapper", { status: "done", task: "Security map ready · 9 nodes", progress: 1 });
  phase("mapped");

  // ---- Attack --------------------------------------------------------------
  phase("attacking");
  agent("attacker", { status: "running", task: "Probing high-risk routes in the sandbox", progress: 0.1 }, 120);
  SCRIPTS.attacking.terminal.forEach((l, i) => {
    term(l);
    agent("attacker", { progress: (i + 1) / SCRIPTS.attacking.terminal.length });
  });
  finding({ status: "reproduced" });
  SCRIPTS.attacking.timeline.forEach(time);
  agent("attacker", { status: "done", task: "1 exploit reproduced · evidence saved", progress: 1 });
  phase("attacked");

  // ---- Defend --------------------------------------------------------------
  phase("defending");
  agent("defender", { status: "running", task: "Tracing the exploit and ranking fixes", progress: 0.1 }, 120);
  finding({ status: "analyzing" });
  SCRIPTS.defending.terminal.forEach((l, i) => {
    term(l);
    agent("defender", { progress: (i + 1) / SCRIPTS.defending.terminal.length });
  });
  SCRIPTS.defending.timeline.forEach(time);
  agent("defender", { status: "done", task: "3 mitigations proposed", progress: 1 });
  phase("defended");

  // ---- Approval gate #1: approve the proposed fix --------------------------
  finding({ status: "awaiting-approval" });
  agent("remediator", { status: "awaiting-approval", task: "Waiting for you to approve the mitigation" });
  beats.push({ t: "gate", approvalId: "approve-fix", delay: 300 });

  // ---- Remediate -----------------------------------------------------------
  phase("remediating");
  agent("remediator", { status: "running", task: "Writing the fix and a regression test", progress: 0.1 }, 120);
  finding({ status: "remediating" });
  SCRIPTS.remediating.terminal.forEach((l, i) => {
    term(l);
    agent("remediator", { progress: (i + 1) / (SCRIPTS.remediating.terminal.length + SCRIPTS.testing.terminal.length) });
  });
  SCRIPTS.remediating.timeline.forEach(time);

  // ---- Test ----------------------------------------------------------------
  phase("testing");
  SCRIPTS.testing.terminal.forEach((l) => term(l));
  SCRIPTS.testing.timeline.forEach(time);
  agent("remediator", { status: "done", task: "Fix committed · 156 tests green", progress: 1 });

  // ---- Verify (independent) ------------------------------------------------
  phase("verifying");
  agent("verifier", { status: "running", task: "Replaying the original attack against the fix", progress: 0.1 }, 120);
  finding({ status: "verifying" });
  SCRIPTS.verifying.terminal.forEach((l, i) => {
    term(l);
    agent("verifier", { progress: (i + 1) / SCRIPTS.verifying.terminal.length });
  });
  beats.push({ t: "verify", patch: { outcome: "verified" }, delay: STEP });
  SCRIPTS.verifying.timeline.forEach(time);
  finding({ status: "verified" });
  agent("verifier", { status: "done", task: "Verified · exploit no longer works", progress: 1 });
  phase("verified");

  // ---- Approval gate #2: approve the merge / ship --------------------------
  beats.push({ t: "gate", approvalId: "approve-merge", delay: 300 });
  time({ time: "09:57", actor: "You", kind: "human", text: "Approved the merge of fix/admin-export-authz into main" });

  return beats;
}

export function applyBeat(s: ArcadeState, beat: Beat): ArcadeState {
  switch (beat.t) {
    case "phase":
      return { ...s, phase: beat.phase };
    case "term":
      return { ...s, terminal: [...s.terminal, beat.line] };
    case "timeline":
      return {
        ...s,
        timeline: [...s.timeline, beat.ev],
        finding: { ...s.finding, timeline: [...s.finding.timeline, beat.ev] },
      };
    case "agent":
      return { ...s, agents: { ...s.agents, [beat.kind]: { ...s.agents[beat.kind], ...beat.patch } } };
    case "reveal":
      return { ...s, revealedNodes: beat.n };
    case "finding":
      return { ...s, finding: { ...s.finding, ...beat.patch } };
    case "verify":
      return { ...s, finding: { ...s.finding, verification: { ...s.finding.verification, ...beat.patch } } };
    case "gate": {
      // A live run carries its own def; the demo falls back to the static table.
      const def = beat.def ?? APPROVAL_DEFS[beat.approvalId];
      if (s.approvals.some((a) => a.id === beat.approvalId)) return s;
      return { ...s, approvals: [...s.approvals, { id: beat.approvalId, status: "pending", ...def }] };
    }
    default:
      return s;
  }
}
