// GENERATED by scripts/sync-core.mjs from packages/core/src/scanner.ts — do not edit here.
/**
 * The scanner — reads an imported workspace and applies the rule set.
 *
 * It is read-only: it lists directories and reads text files through the same
 * WorkspaceFs the explorer uses, matches rules against the source, and returns
 * where each weakness sits. It never writes, executes, or reaches the network.
 *
 * This is the "attack in a sandbox" made concrete and safe: the target is the
 * user's own code, analysed statically in the browser/desktop process, with no
 * side effects on the project or any live system.
 */
import { baseName, crawl, extOf, MAX_TEXT_BYTES, type FileContent, type WorkspaceFs } from "./fs";
import { bySeverity, RULES, type Rule, type RuleMatch } from "./rules";

/** One rule firing at one place, with the file's text kept for the agents. */
export interface Hit {
  rule: Rule;
  path: string;
  match: RuleMatch;
}

export interface Scan {
  hits: Hit[];
  /** file text keyed by path, for hits only — so agents can build real diffs. */
  sources: Record<string, string>;
  filesScanned: number;
  bytesScanned: number;
  /** language name → file count, for the project profile. */
  languages: Record<string, number>;
  /** every indexed file path (heavy dirs excluded). */
  paths: string[];
  truncated: boolean;
}

export interface ScanOptions {
  /** "source" skips tests, fixtures and generated config to cut noise. */
  scope: "all" | "source";
}

export interface ScanProgress {
  filesScanned: number;
  total: number;
  hits: number;
  current?: string;
}

const MAX_FILES = 4000;
const MAX_HITS = 400;
const MAX_HITS_PER_RULE_FILE = 20;
const MAX_LINE_LEN = 800;

/** Never worth scanning as source. */
const SKIP_EXT = new Set([
  "png", "jpg", "jpeg", "gif", "webp", "svg", "ico", "bmp", "avif",
  "lock", "map", "min.js", "woff", "woff2", "ttf", "otf", "eot",
  "pdf", "zip", "gz", "tar", "exe", "dll", "so", "dylib", "bin",
  "mp4", "mp3", "mov", "wav", "ogg", "class", "pyc",
]);

const SOURCE_SKIP = /(?:^|\/)(?:test|tests|__tests__|__mocks__|spec|e2e|fixtures?|examples?|stories|\.storybook|docs?|public|assets)(?:\/|$)/i;
const SKIP_NAME = /(?:\.min\.|\.d\.ts$|package-lock\.json$|yarn\.lock$|pnpm-lock\.yaml$)/i;

const LANG_BY_EXT: Record<string, string> = {
  ts: "TypeScript", tsx: "TypeScript", mts: "TypeScript", cts: "TypeScript",
  js: "JavaScript", jsx: "JavaScript", mjs: "JavaScript", cjs: "JavaScript",
  py: "Python", rb: "Ruby", go: "Go", rs: "Rust", java: "Java", kt: "Kotlin",
  php: "PHP", cs: "C#", c: "C", h: "C", cpp: "C++", swift: "Swift",
  sql: "SQL", sh: "Shell", yml: "YAML", yaml: "YAML", json: "JSON",
};

const shouldSkip = (path: string, scope: ScanOptions["scope"]) => {
  if (SKIP_EXT.has(extOf(path)) || SKIP_NAME.test(path)) return true;
  if (scope === "source" && SOURCE_SKIP.test(path)) return true;
  return false;
};

/** Apply every applicable rule to one file's text. */
function scanFile(rule: Rule, path: string, text: string, lines: string[]): RuleMatch[] {
  if (rule.ext && !rule.ext.includes(extOf(path))) return [];

  if (rule.fileScan) {
    try {
      return rule.fileScan(text, path).slice(0, MAX_HITS_PER_RULE_FILE);
    } catch {
      return [];
    }
  }
  if (!rule.pattern) return [];

  const out: RuleMatch[] = [];
  for (let i = 0; i < lines.length && out.length < MAX_HITS_PER_RULE_FILE; i++) {
    const line = lines[i];
    if (line.length > MAX_LINE_LEN) continue;
    rule.pattern.lastIndex = 0;
    const m = rule.pattern.exec(line);
    if (!m) continue;
    if (rule.refine && !rule.refine(line, path)) continue;
    out.push({ line: i + 1, column: m.index, excerpt: line.trim().slice(0, 240), captured: m[0] });
  }
  return out;
}

/**
 * Crawl the workspace and return every rule hit. Cooperative: it checks
 * `isCancelled` and yields progress so the UI stays responsive on large repos.
 */
export async function scanWorkspace(
  fs: WorkspaceFs,
  opts: ScanOptions,
  isCancelled: () => boolean,
  onProgress?: (p: ScanProgress) => void,
): Promise<Scan> {
  const paths = await crawl(fs, isCancelled);
  const candidates = paths.filter((p) => !shouldSkip(p, opts.scope)).slice(0, MAX_FILES);

  const hits: Hit[] = [];
  const sources: Record<string, string> = {};
  const languages: Record<string, number> = {};
  let filesScanned = 0;
  let bytesScanned = 0;
  let truncated = false;

  for (const path of candidates) {
    if (isCancelled()) break;
    if (hits.length >= MAX_HITS) {
      truncated = true;
      break;
    }

    let content: FileContent;
    try {
      content = await fs.read(path);
    } catch {
      continue;
    }
    if (content.kind !== "text" || content.size > MAX_TEXT_BYTES) continue;

    filesScanned++;
    bytesScanned += content.size;
    let lang = LANG_BY_EXT[extOf(path)];
    if (!lang && baseName(path).toLowerCase() === "dockerfile") lang = "Dockerfile";
    if (lang) languages[lang] = (languages[lang] ?? 0) + 1;

    const lines = content.text.split("\n");
    let fileHadHit = false;
    for (const rule of RULES) {
      for (const match of scanFile(rule, path, content.text, lines)) {
        hits.push({ rule, path, match });
        fileHadHit = true;
        if (hits.length >= MAX_HITS) break;
      }
      if (hits.length >= MAX_HITS) break;
    }
    if (fileHadHit) sources[path] = content.text;

    if (onProgress && filesScanned % 25 === 0) {
      onProgress({ filesScanned, total: candidates.length, hits: hits.length, current: path });
    }
  }

  // Strongest first, then by location so the ordering is stable.
  hits.sort((a, b) => bySeverity(a.rule, b.rule) || a.path.localeCompare(b.path) || a.match.line - b.match.line);

  onProgress?.({ filesScanned, total: candidates.length, hits: hits.length });
  return { hits, sources, filesScanned, bytesScanned, languages, paths, truncated };
}
