// GENERATED by scripts/sync-core.mjs from packages/core/src/store.ts — do not edit here.
"use client";
/**
 * useArcadeRun — the demo run engine.
 *
 * A run is an ordered list of "beats" (pure state transforms) played on a
 * timer. The driver pauses at approval "gates" until a human approves, which
 * is what makes the human-in-the-loop story real rather than cosmetic.
 *
 * The same state shape (ArcadeState) would be produced by a real agent
 * backend; only the source of the beats would change.
 */
import { useCallback, useEffect, useMemo, useReducer, useRef } from "react";
import type { ArcadeState } from "./types";
import { applyBeat, buildBeats, freshState, type Beat } from "./engine";

interface RunState {
  s: ArcadeState;
  cursor: number;
  running: boolean;
}

type Action =
  | { type: "APPLY"; beat: Beat }
  | { type: "ADVANCE" }
  | { type: "START" }
  | { type: "SET_RUNNING"; running: boolean }
  | { type: "RESET" }
  | { type: "APPROVE"; id: string }
  | { type: "REJECT"; id: string }
  | { type: "REQUEST_DESTRUCTIVE" }
  | { type: "SET_PROVIDER"; id: string; connected: boolean };

function reducer(state: RunState, action: Action): RunState {
  switch (action.type) {
    case "START":
      return { ...state, running: true };
    case "SET_RUNNING":
      return { ...state, running: action.running };
    case "ADVANCE":
      return { ...state, cursor: state.cursor + 1 };
    case "APPLY":
      return { ...state, s: applyBeat(state.s, action.beat) };
    case "RESET":
      return { s: freshState(), cursor: 0, running: false };
    case "APPROVE":
      return {
        ...state,
        running: true,
        s: {
          ...state.s,
          approvals: state.s.approvals.map((a) => (a.id === action.id ? { ...a, status: "approved" } : a)),
        },
      };
    case "REJECT":
      // Drop the approval and pause. Resuming re-creates the gate's pending
      // approval, so a reject sends you back to the decision rather than a
      // dead end. (For a destructive request, this simply cancels it.)
      return {
        ...state,
        running: false,
        s: {
          ...state.s,
          approvals: state.s.approvals.filter((a) => a.id !== action.id),
        },
      };
    case "REQUEST_DESTRUCTIVE":
      if (state.s.approvals.some((a) => a.id === "reset-sandbox" && a.status === "pending")) return state;
      return {
        ...state,
        s: {
          ...state.s,
          approvals: [
            ...state.s.approvals,
            {
              id: "reset-sandbox",
              kind: "destructive",
              status: "pending",
              title: "Reset the isolated test environment",
              reason: "The attacker agent wants to delete and rebuild the disposable sandbox database.",
              target: "sandbox-7f2c · postgres (disposable)",
            },
          ],
        },
      };
    case "SET_PROVIDER":
      return {
        ...state,
        s: {
          ...state.s,
          providers: state.s.providers.map((p) => (p.id === action.id ? { ...p, connected: action.connected } : p)),
        },
      };
    default:
      return state;
  }
}

export function useArcadeRun() {
  const beats = useMemo(() => buildBeats(), []);
  const [state, dispatch] = useReducer(reducer, undefined, () => ({ s: freshState(), cursor: 0, running: false }));
  const timer = useRef<ReturnType<typeof setTimeout> | undefined>(undefined);

  useEffect(() => {
    if (!state.running) return;
    if (state.cursor >= beats.length) {
      dispatch({ type: "SET_RUNNING", running: false });
      return;
    }
    const beat = beats[state.cursor];

    // Pause at a gate whose approval has not been granted yet.
    if (beat.t === "gate") {
      const appr = state.s.approvals.find((a) => a.id === beat.approvalId);
      if (!appr) {
        // create the pending approval, then stop and wait
        dispatch({ type: "APPLY", beat });
        dispatch({ type: "SET_RUNNING", running: false });
        return;
      }
      if (appr.status === "pending") {
        dispatch({ type: "SET_RUNNING", running: false });
        return;
      }
      if (appr.status === "rejected") {
        dispatch({ type: "SET_RUNNING", running: false });
        return;
      }
      // approved → skip past the gate
      dispatch({ type: "ADVANCE" });
      return;
    }

    timer.current = setTimeout(() => {
      dispatch({ type: "APPLY", beat });
      dispatch({ type: "ADVANCE" });
    }, beat.delay);
    return () => {
      if (timer.current) clearTimeout(timer.current);
    };
  }, [state.running, state.cursor, state.s.approvals, beats]);

  const start = useCallback(() => dispatch({ type: "START" }), []);
  const reset = useCallback(() => dispatch({ type: "RESET" }), []);
  const approve = useCallback((id: string) => dispatch({ type: "APPROVE", id }), []);
  const reject = useCallback((id: string) => dispatch({ type: "REJECT", id }), []);
  const requestDestructive = useCallback(() => dispatch({ type: "REQUEST_DESTRUCTIVE" }), []);
  const dismissApproval = useCallback((id: string) => dispatch({ type: "APPROVE", id }), []);
  const setProvider = useCallback(
    (id: string, connected: boolean) => dispatch({ type: "SET_PROVIDER", id, connected }),
    [],
  );

  const pendingApproval = state.s.approvals.find((a) => a.status === "pending");
  const progress = Math.min(1, state.cursor / beats.length);

  return {
    state: state.s,
    running: state.running,
    progress,
    pendingApproval,
    start,
    reset,
    approve,
    reject,
    requestDestructive,
    setProvider,
    dismissApproval,
  };
}

export type ArcadeRun = ReturnType<typeof useArcadeRun>;
