/**
 * Vendors Arcade's platform-neutral engine into this app.
 *
 *   packages/core/src          → src/core          (model, demo, run store, scanner, rules, fixes, GitHub writes)
 *   packages/agents/src        → src/agents        (mapper, attacker, defender, remediator, verifier, provider)
 *   packages/orchestrator/src  → src/orchestrator  (the assessment pipeline)
 *
 * Those packages are plain TypeScript with no DOM or Next.js dependency, so the
 * phone runs the very same code as the desktop app. They stay the source of
 * truth: edit there, then run `npm run sync:core`. The copies are committed so
 * the app builds on its own (EAS uploads only this folder, and it is not an npm
 * workspace).
 *
 * Only the files the entry points actually import are copied. The packages
 * import each other through `@arcade/<package>/<file>` aliases; those are
 * rewritten to relative paths, so neither Metro nor tsc needs an alias.
 *
 *   node scripts/sync-core.mjs           write the copies
 *   node scripts/sync-core.mjs --check   exit 1 if any copy is stale, missing or orphaned
 */
import { mkdir, readdir, readFile, rm, writeFile } from "node:fs/promises";
import { existsSync } from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const packages = path.resolve(here, "../../../packages");
const out = path.resolve(here, "../src");
const check = process.argv.includes("--check");

const PACKAGES = ["core", "agents", "orchestrator"];

/** Where the walk starts. Everything these import (within the three packages) comes along. */
const ENTRY = {
  core: ["types.ts", "demo.ts", "engine.ts", "store.ts", "fs.ts", "highlight.ts", "scanner.ts", "rules.ts", "fixes.ts", "github-write.ts", "finding-text.ts"],
  agents: "*",
  orchestrator: "*",
};

/**
 * Browser- or desktop-only APIs that do not exist in React Native. A vendored
 * file that uses one fails the sync, so it cannot slip in through a new import.
 */
const FORBIDDEN = [/\bwindow\.arcade\b/, /\bwindow\.show\w+Picker\b/, /\bindexedDB\./, /\blocalStorage\./, /\bsessionStorage\./, /\bdocument\.(?:createElement|querySelector|getElementById|body|cookie)\b/, /\bURL\.createObjectURL\b/];
/** Known, reviewed exceptions: `handleFs` needs a browser directory handle, which the phone never has, so it is never called. */
const ALLOWED = { "core/fs.ts": [/\bURL\.createObjectURL\b/] };

const ALIAS = /(["'])@arcade\/(core|agents|orchestrator)\/([^"']+)\1/g;
const RELATIVE = /(?:from\s+|import\s*\(\s*|import\s+)(["'])(\.\/[^"']+)\1/g;

const sourceOf = (pkg, file) => path.join(packages, pkg, "src", file);

/** Every file reachable from the entry points, as "pkg/file.ts". */
async function closure() {
  const queue = [];
  for (const pkg of PACKAGES) {
    const files = ENTRY[pkg] === "*" ? (await readdir(path.join(packages, pkg, "src"))).filter((f) => f.endsWith(".ts") && !f.endsWith(".test.ts")) : ENTRY[pkg];
    for (const f of files) queue.push(`${pkg}/${f}`);
  }
  const seen = new Set();
  while (queue.length) {
    const id = queue.shift();
    if (seen.has(id)) continue;
    const [pkg, file] = id.split("/");
    if (!existsSync(sourceOf(pkg, file))) throw new Error(`${id} is imported but does not exist in packages/${pkg}/src`);
    seen.add(id);
    const text = await readFile(sourceOf(pkg, file), "utf8");
    for (const m of text.matchAll(ALIAS)) queue.push(`${m[2]}/${m[3]}.ts`);
    for (const m of text.matchAll(RELATIVE)) queue.push(`${pkg}/${m[2].slice(2)}.ts`);
  }
  return [...seen].sort();
}

/** The vendored text of one file: banner + source with aliases made relative. */
async function render(id) {
  const [pkg, file] = id.split("/");
  const source = await readFile(sourceOf(pkg, file), "utf8");

  const allowed = ALLOWED[id] ?? [];
  for (const re of FORBIDDEN) {
    if (re.test(source) && !allowed.some((a) => a.source === re.source)) {
      throw new Error(`${id} uses ${re.source}, which does not exist in React Native. Drop it from the sync or move that code out of the shared file.`);
    }
  }

  const rewritten = source.replace(ALIAS, (_, quote, toPkg, toFile) => `${quote}${toPkg === pkg ? "./" : `../${toPkg}/`}${toFile}${quote}`);
  if (rewritten.includes("@arcade/")) throw new Error(`${id} still has an @arcade/ import after rewriting — extend the sync script to cover that package.`);
  return `// GENERATED by scripts/sync-core.mjs from packages/${pkg}/src/${file} — do not edit here.\n${rewritten}`;
}

const sameText = (a, b) => a.replace(/\r\n/g, "\n") === b.replace(/\r\n/g, "\n");

const ids = await closure();
const problems = [];

for (const id of ids) {
  const target = path.join(out, id);
  const next = await render(id);
  const current = existsSync(target) ? await readFile(target, "utf8") : null;
  if (current != null && sameText(current, next)) continue;
  if (check) {
    problems.push(`${current == null ? "missing" : "stale  "}  src/${id}`);
    continue;
  }
  await mkdir(path.dirname(target), { recursive: true });
  await writeFile(target, next);
  console.log(`${current == null ? "added " : "synced"}  src/${id}`);
}

// A generated file whose source is gone (or no longer imported) must not linger.
for (const pkg of PACKAGES) {
  const dir = path.join(out, pkg);
  if (!existsSync(dir)) continue;
  for (const file of await readdir(dir)) {
    if (ids.includes(`${pkg}/${file}`)) continue;
    const text = await readFile(path.join(dir, file), "utf8").catch(() => "");
    if (!text.startsWith("// GENERATED by scripts/sync-core.mjs")) continue; // hand-written neighbour, leave it
    if (check) problems.push(`orphan   src/${pkg}/${file}`);
    else {
      await rm(path.join(dir, file));
      console.log(`removed src/${pkg}/${file}`);
    }
  }
}

if (check) {
  if (problems.length) {
    console.error(`Vendored engine is out of date (${problems.length}):\n  ${problems.join("\n  ")}\nRun \`npm run sync:core\`.`);
    process.exit(1);
  }
  console.log(`Vendored engine is up to date (${ids.length} files).`);
} else {
  console.log(`${ids.length} files vendored into src/{${PACKAGES.join(",")}}.`);
}
