/**
 * Copies Arcade's platform-neutral core from the web app into src/core.
 *
 * The data model, demo data, run engine and highlighter are plain TypeScript
 * with no DOM or Next.js dependency, so the mobile app runs the very same code
 * as the ADE. The web app stays the source of truth: edit there, then run
 * `npm run sync:core`. The copies are committed so the app builds on its own
 * (EAS uploads only this folder).
 */
import { mkdir, readFile, writeFile } from "node:fs/promises";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const from = path.resolve(here, "../../../packages/core/src");
const to = path.resolve(here, "../src/core");

const FILES = ["types.ts", "demo.ts", "engine.ts", "store.ts", "fs.ts", "highlight.ts"];

await mkdir(to, { recursive: true });
for (const file of FILES) {
  const source = await readFile(path.join(from, file), "utf8");
  const banner = `// GENERATED by scripts/sync-core.mjs from packages/core/src/${file} — do not edit here.\n`;
  await writeFile(path.join(to, file), banner + source);
  console.log(`synced ${file}`);
}
