// Builds packages/cli/engine.mjs — the monorepo's TypeScript engine as one
// dependency-free ESM file the CLI, the MCP server and the desktop app can load.
//
//   node scripts/build-engine.mjs           write engine.mjs
//   node scripts/build-engine.mjs --check   exit 1 if the committed engine.mjs is stale
//
// The bundle is committed on purpose: `npm pack` and electron-builder copy the
// flat .mjs files as they are, with no build step. `--check` (run by `prepack`
// and the test suite) is what keeps the committed copy honest.
//
// esbuild comes from the monorepo root; it is a build-time tool only and is not
// a dependency of the published package. Inside an installed package (no
// monorepo sources next to it) there is nothing to rebuild, so both modes exit 0.

import fs from "node:fs";
import path from "node:path";
import { fileURLToPath } from "node:url";

const here = path.dirname(fileURLToPath(import.meta.url));
const cliRoot = path.resolve(here, "..");
const packages = path.resolve(cliRoot, "..");
const outFile = path.join(cliRoot, "engine.mjs");
const check = process.argv.includes("--check");

const BANNER = [
  "// GENERATED by scripts/build-engine.mjs — do not edit.",
  "// Source: packages/core, packages/agents (TypeScript). Rebuild with: npm run build:engine",
  "",
].join("\n");

/** Files that must never reach the bundle: they pull in React, the DOM or browser storage. */
const FORBIDDEN = /(?:^|\/)(?:store|github|workspace|cloud-sync|engine|demo)\.tsx?$|node_modules/;

const sourcesPresent = fs.existsSync(path.join(packages, "core", "src", "scanner.ts")) && fs.existsSync(path.join(packages, "agents", "src", "mapper.ts"));
if (!sourcesPresent) {
  console.log("build-engine: monorepo sources not found next to this package; using the engine.mjs that shipped with it.");
  process.exit(fs.existsSync(outFile) ? 0 : 1);
}

let esbuild;
try {
  esbuild = await import("esbuild");
} catch {
  console.error("build-engine: esbuild is not installed. Run `npm install` at the monorepo root first.");
  process.exit(1);
}

const { version } = JSON.parse(fs.readFileSync(path.join(cliRoot, "package.json"), "utf8"));

const result = await esbuild.build({
  absWorkingDir: cliRoot, // keeps the path comments in the output relative, so the bundle is identical on every machine
  entryPoints: ["scripts/engine-entry.ts"],
  bundle: true,
  write: false,
  format: "esm",
  platform: "node",
  target: "node20",
  outfile: "engine.mjs",
  charset: "utf8",
  legalComments: "none",
  metafile: true,
  logLevel: "warning",
  alias: {
    "@arcade/core": path.join(packages, "core", "src"),
    "@arcade/agents": path.join(packages, "agents", "src"),
    "@arcade/orchestrator": path.join(packages, "orchestrator", "src"),
  },
  define: { __ARCADE_VERSION__: JSON.stringify(version) },
});

const inputs = Object.keys(result.metafile.inputs).map((p) => p.replace(/\\/g, "/"));
const bad = inputs.filter((p) => FORBIDDEN.test(p));
if (bad.length) {
  console.error(`build-engine: these files must not be bundled into the CLI engine:\n  ${bad.join("\n  ")}`);
  process.exit(1);
}

const code = BANNER + result.outputFiles[0].text;
// The bundle has to stand alone: any surviving import means a dependency leaked in.
const leaked = Object.values(result.metafile.outputs).flatMap((o) => o.imports ?? []);
if (leaked.length) {
  console.error(`build-engine: the bundle still imports ${leaked.map((i) => i.path).join(", ")}; the engine must be dependency-free.`);
  process.exit(1);
}

const normalize = (s) => s.replace(/\r\n/g, "\n");
const current = fs.existsSync(outFile) ? fs.readFileSync(outFile, "utf8") : null;
const fresh = current != null && normalize(current) === normalize(code);

if (check) {
  if (fresh) {
    console.log(`build-engine: engine.mjs is up to date (${inputs.length} source files, v${version}).`);
  } else {
    console.error("build-engine: engine.mjs is stale — the engine sources (or the package version) changed since it was built.\n  Run: npm run build:engine -w packages/cli   and commit the result.");
    process.exit(1);
  }
} else if (fresh) {
  console.log("build-engine: engine.mjs already up to date.");
} else {
  fs.writeFileSync(outFile, code);
  console.log(`build-engine: wrote engine.mjs (${(code.length / 1024).toFixed(1)} KB from ${inputs.length} source files, v${version}).`);
}
