import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import fs from "node:fs";
import path from "node:path";
import { test } from "node:test";
import * as engine from "../engine.mjs";
import { CLI_DIR } from "./helpers.mjs";

const sources = fs.existsSync(path.join(CLI_DIR, "..", "core", "src", "scanner.ts"));
const esbuild = fs.existsSync(path.join(CLI_DIR, "..", "..", "node_modules", "esbuild", "package.json"));

test("the committed engine bundle matches the TypeScript sources", { skip: !(sources && esbuild) && "monorepo sources or esbuild not available" }, () => {
  const r = spawnSync(process.execPath, [path.join(CLI_DIR, "scripts", "build-engine.mjs"), "--check"], { encoding: "utf8" });
  assert.equal(r.status, 0, `${r.stdout}${r.stderr}`);
});

test("the bundle is generated, dependency-free and free of React", () => {
  const code = fs.readFileSync(path.join(CLI_DIR, "engine.mjs"), "utf8");
  assert.match(code, /^\/\/ GENERATED by scripts\/build-engine\.mjs/);
  assert.doesNotMatch(code, /^\s*import\s/m, "the engine must not import anything");
  assert.doesNotMatch(code, /\brequire\(/);
  assert.doesNotMatch(code, /from\s+["']react["']|useSyncExternalStore|localStorage/);
});

test("the engine exports what the CLI and MCP server use", () => {
  for (const name of ["scanWorkspace", "RULES", "RULES_BY_ID", "bySeverity", "ruleOf", "matchRule", "isConcrete", "ruleEdit", "applyEdit", "diffTexts", "verifyFile", "mapProject", "mapSurface", "reproduce", "defend", "remediate", "verify", "LOCAL_PROVIDER", "commitFiles", "openPullRequest", "repoAccess", "githubRepoOf", "desktopFs", "ENGINE_VERSION"]) {
    assert.ok(name in engine, `engine.mjs is missing ${name}`);
  }
  assert.equal(engine.RULES.length, 14);
  const pkg = JSON.parse(fs.readFileSync(path.join(CLI_DIR, "package.json"), "utf8"));
  assert.equal(engine.ENGINE_VERSION, pkg.version);
  assert.equal(engine.githubRepoOf("git@github.com:ayushagarwalhere/arcade.git"), "ayushagarwalhere/arcade");
});

test("every runtime module is a flat .mjs file, because the desktop app copies only those", () => {
  const pkg = JSON.parse(fs.readFileSync(path.join(CLI_DIR, "package.json"), "utf8"));
  assert.deepEqual(pkg.files, ["*.mjs", "README.md", "LICENSE"]);
  const flat = fs.readdirSync(CLI_DIR).filter((f) => f.endsWith(".mjs"));
  for (const file of flat) {
    const src = fs.readFileSync(path.join(CLI_DIR, file), "utf8");
    for (const m of src.matchAll(/^\s*(?:import|export)\s[^;]*?from\s+["'](\.[^"']+)["']/gm)) {
      assert.match(m[1], /^\.\/[\w.-]+\.mjs$/, `${file} imports ${m[1]}, which is not a flat sibling module`);
      assert.ok(flat.includes(m[1].slice(2)), `${file} imports ${m[1]}, which does not exist`);
    }
  }
  assert.equal(Object.keys(pkg.dependencies ?? {}).length, 0, "the package must stay dependency-free");
});
